// products.js
const products = [
  {
    id: 1,
    name: "Slim Fit Shirt-Lavender",
    price: 19,
    category: "shirts",
    image: "./images/product1.jpeg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Sunglasses-Black",
    price: 30,
    category: "accessories",
    image: "./images/product6.jpeg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Regular Shirt-Black",
    price: 24,
    category: "shirts",
    image: "./images/product5.jpeg",
    quantity: 1,
  },
  {
    id: 4,
    name: "NYC Cap",
    price: 100,
    category: "accessories",
    image: "./images/product7.jpeg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Stylish rings set of 3",
    price: 50,
    category: "accessories",
    image: "./images/product8.jpeg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Fabric belt-Black",
    price: 60,
    category: "accessories",
    image: "./images/product9.jpeg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Regular shirt-Black",
    price: 100,
    category: "shirt",
    image: "./images/product3.jpeg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Stylish Chain set",
    price: 85,
    category: "accessories",
    image: "./images/product10.jpeg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Slim fit tshirt-Olive",
    price: 35,
    category: "shirt",
    image: "./images/product12.jpeg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Regular Shirt-Thistle",
    price: 100,
    category: "shirt",
    image: "./images/product2.jpeg",
    quantity: 1,
  },
  {
    id: 11,
    name: "Regular Fit Jeans-Black",
    price: 45,
    category: "pants",
    image: "./images/product18.jpeg",
    quantity: 1,
  },
  {
    id: 12,
    name: "H&M Filp-flops-Black",
    price: 30,
    category: "shoes",
    image: "./images/product35.jpeg",
    quantity: 1,
  },
  {
    id: 13,
    name: "Slim fit tshirt-Maroon",
    price: 38,
    category: "shirt",
    image: "./images/product14.jpeg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Rolex Watch",
    price: 10000,
    category: "accessories",
    image: "./images/product30.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "Addidas Shoes",
    price: 50,
    category: "shoes",
    image: "./images/product33.jpg",
    quantity: 1,
  },
];

export default products;
